<a href="https://colab.research.google.com/github/anyfish/pandas_numpy/blob/main/8_concat_append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade pandas

In [ ]:
import pandas as pd
import numpy as np
pd.__version__

'1.3.5'

# Numpy

In [ ]:
# Cambiamos el número de decimales 
pd.options.display.float_format = '{:.2f}'.format

In [ ]:
# Cambiamos el número de decimales 
np.set_printoptions(precision=1)

In [ ]:
# Creamos arreglos numpy con datos aleatorios
x1 = np.random.rand(2,5)*10
x1

array([[3.3, 9.5, 0.7, 2.9, 3.6],
       [0.3, 6.2, 7.9, 3.2, 9.1]])

In [ ]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.3, -0.8, -0.6, -0.9, -0.8],
       [-0.6, -0.8, -0. , -0.8, -0.9]])

In [ ]:
# Concatenamos 2 arrglos de numpy
np.concatenate([x1,x2])

array([[ 3.3,  9.5,  0.7,  2.9,  3.6],
       [ 0.3,  6.2,  7.9,  3.2,  9.1],
       [-0.3, -0.8, -0.6, -0.9, -0.8],
       [-0.6, -0.8, -0. , -0.8, -0.9]])

In [ ]:
# Vemos la dimenciones de arreglo concatenado
np.concatenate([x1,x2]).shape

(4, 5)

In [ ]:
# Cambiamos las dimensiones del arreglo concatenado
np.concatenate([x1,x2], axis = 1)

array([[ 3.3,  9.5,  0.7,  2.9,  3.6, -0.3, -0.8, -0.6, -0.9, -0.8],
       [ 0.3,  6.2,  7.9,  3.2,  9.1, -0.6, -0.8, -0. , -0.8, -0.9]])

In [ ]:
# Vemos las dimensiones que tiene el arreglo concatenado
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

# PANDAS

In [ ]:
# Creamos series con un cierto indice y con datos de arrglo de numpy
s1 = pd.Series(x1[0],index = ['a','b','c','d','e'])
s1

a   3.33
b   9.53
c   0.67
d   2.92
e   3.57
dtype: float64

In [ ]:
s2 = pd.Series(x2[0],index = ['c','d','e','f','g'])
s2

c   -0.32
d   -0.77
e   -0.59
f   -0.91
g   -0.84
dtype: float64

In [ ]:
# Conatenamos 2 series de pandas de forma de columnas
pd.concat([s1,s2], axis=1)

0     1
a 3.33   NaN
b 9.53   NaN
c 0.67 -0.32
d 2.92 -0.77
e 3.57 -0.59
f  NaN -0.91
g  NaN -0.84

In [ ]:
# Reiniciamos el indice (Colocando como columna)
s1.reset_index()

index    0
0     a 3.33
1     b 9.53
2     c 0.67
3     d 2.92
4     e 3.57

In [ ]:
# Reiniciamos el indice (Borrandolo)
s1.reset_index(drop=True)

0   3.33
1   9.53
2   0.67
3   2.92
4   3.57
dtype: float64

In [ ]:
# Concatenamos las series borrando sus indices y colocandolo como columnas 
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 3.33 -0.32
1 9.53 -0.77
2 0.67 -0.59
3 2.92 -0.91
4 3.57 -0.84

In [ ]:
# Creamos un nuevo DF con valores aletorios y en un cierto shape con las columnas a y b
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 5.71 8.03
1 9.64 7.17
2 6.72 9.70

In [ ]:
# Creamos un DF igual al anterior pero con un indice de 2,3,4
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.32 -0.98
3 -0.64 -0.18
4 -0.49 -0.93

In [ ]:
# Concatenamos 2 DF
pd.concat([df1,df2])

a     b
0  9.29  5.82
1  7.95  2.05
2  6.98  8.74
2 -0.32 -0.98
3 -0.64 -0.18
4 -0.49 -0.93

In [ ]:
# Concatenamos 2 DF y los colocamos como columnas
pd.concat([df1,df2], axis=1)

a    b     a     b
0 9.29 5.82   NaN   NaN
1 7.95 2.05   NaN   NaN
2 6.98 8.74 -0.32 -0.98
3  NaN  NaN -0.64 -0.18
4  NaN  NaN -0.49 -0.93

In [ ]:
# Concatenamos 2 DF, en columnas y obtenemos el ejemplar que se repite en ambos DF.
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 6.98 8.74 -0.32 -0.98

In [ ]:
# Concatenamos y reiniciamos indices borradolos
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 9.29 5.82 -0.32 -0.98
1 7.95 2.05 -0.64 -0.18
2 6.98 8.74 -0.49 -0.93

In [ ]:
# Le agregamos 2 veces el mismo DF a df1
df1.append(df2).append(df2)

a     b
0  9.29  5.82
1  7.95  2.05
2  6.98  8.74
2 -0.32 -0.98
3 -0.64 -0.18
4 -0.49 -0.93
2 -0.32 -0.98
3 -0.64 -0.18
4 -0.49 -0.93

In [ ]:
# Cremos una transpues de las columnas x las filas de un DF
df1.T

0    1    2
a 9.29 7.95 6.98
b 5.82 2.05 8.74

In [ ]:
# A la transpues de un DF se le agrega otro DF en transpuesta y eso se coloca en transpuesta
df1.T.append(df2.T).T

a    b     a     b
0 9.29 5.82   NaN   NaN
1 7.95 2.05   NaN   NaN
2 6.98 8.74 -0.32 -0.98
3  NaN  NaN -0.64 -0.18
4  NaN  NaN -0.49 -0.93